name: middleware actions
on:
  push:
    branches:
      - main
env:
  CLUSTER_NAME: devops.abubakaramasa.com
  CLUSTER_STATE: ${{secrets.TEST_STATE_FILE}}

jobs:
  BUILD_AND_PUBLISH_TO_DOCKERHUB:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and publish
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/clockbox:latest


  HELM_DEPLOY:
    needs: BUILD_AND_PUBLISH_TO_DOCKERHUB
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: 'Checkout values file repository'
        uses: actions/checkout@v4
        with:
          repository: 'amasaabu/finchinfra'  # Replace with the actual username and repo
          path: 'finchinfra'  # Use a different path to avoid overwriting files
          token: '${{ secrets.FINCH_INFRA_PAT }}'

      - name: Get Kube config file
        run: |
          mkdir -p ~/.kube
          kops export kubeconfig ${{env.CLUSTER_NAME}} --admin --state=${{env.CLUSTER_STATE}}

      - name: export kube config file
        run: echo "KUBECONFIG=~/.kube/config" >> $GITHUB_ENV
      - name: Verify kubeconfig
        run: kubectl config view

      - name: Deploy via helm
        uses: 'deliverybot/helm@v4'
        with:
          release: 'middleware'
          namespace: 'default'
          chart: .'/finchinfra'
          value-files: "finchinfra/middlewarevalues.yaml"  # Reference the file in the other repo
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
